server:
  port: 8961

eureka:
  environment: dev
  instance:
    hostname: cloud.server1.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://cloud.server2.com:8962/eureka/,http://cloud.server3.com:8963/eureka/
  dashboard:
    path: /dashboard